### ISSUE TITLE
Mobile: when searching or adding a new word, the format of the form should be no caps

### ISSUE THREAD

**Issue by georgetommy** [eickhardt/VoCab#13]

**Comment by eickhardt** [comment]
Fixed 397c67c  & deployed to prod

**Comment by eickhardt** [comment]
This was not satisfactory - an ugly validation message would appear when the input was not an email. Changes has been reverted and I've tried a few other things. The only thing that I have seen work 100% so far is fiddling with the mobile keyboard settings...

**Comment by georgetommy** [comment]
Works well on mobile now (on my phone at least)
